### PR TITLE
Split jca into separate module, restore sample code, fix dependencies, increase version to 1.3

### PR DESCRIPTION
**Pull request by soc**
This resolves the issues mentioned in #2, the only thing that's left is publishing it and making sure other libraries (e. g. Geotools) update their version.

### CODE REVIEW

**Comment by aaime** [comment]
The pull request touches all files, please avoid and leave only the actual changes, without reformatting or changing newlines.

**Comment by soc** [comment]
@aaime damn ... is there a way to make git ignore whitespace changes? Because I fear I have to redo everything from scratch again. :-/

**Comment by soc** [comment]
@aaime I tried https://stackoverflow.com/questions/13793241/make-git-undo-any-whitespace-only-changes and https://stackoverflow.com/questions/3515597/add-only-non-whitespace-changes without success, it seems like moving files breaks the approach proposed in those.

Do you have an idea how to fix this?

**Comment by soc** [comment]
@aaime I think I got everything fixed, could you have a look?

**Comment by aaime** [comment]
I know it's here, but I'm way overloaded, won't find time to look at it for a while.

**Comment by soc** [comment]
Thanks @aaime!

Do you have a plan on when to release the new artifact?

Thanks

Simon

**Comment by aaime** [comment]
It's released already, under the new groupId it.geosolutions.jgridshift. PR to upgrade GeoTools master here: https://github.com/geotools/geotools/pull/2857
I have no plans on upgrading other branches, but if you want, can make PRs yourself.

**Comment by soc** [comment]
@aaime Mhhh, I can't resolve this artifact – is there some delay until it shows up on Maven Central/elsewhere?

**Pull request merged**
